### ISSUE TITLE
Example apps

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/Huxley#10]
Write some example applications to show what can be done with the APIs:
- Maybe an installable mobile JavaScript web app using Backbone.js and jQuery mobile.
- Or a native android / iOS / win / mac app using mono / Xamarin with push notifications.
- IoT project with Raspberry Pi / Spark / Philips Hue for an ambient information radiator?

**Comment by jpsingleton** [comment]
https://github.com/Blinkinlabs/BlinkyTape_Python/blob/master/Huxley_UK_Rail_Station_Delays.py

**Comment by OliPicard** [comment]
Hey James, I have created a UKStation app if you wanted another python example. https://github.com/OliPicard/UKStationLive
