### ISSUE TITLE
Support station names as well as CRS codes

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/Huxley#30]
Lookup station name against list of CRS codes. Use NRE web service or pull flat CSV file?

Support London as all London terminals. And maybe other locations with multiple stations.

**Comment by jpsingleton** [comment]
CRS codes are available here http://www.nationalrail.co.uk/static/documents/content/station_codes.csv

**Comment by jpsingleton** [comment]
London terminals handled in delays action so far https://github.com/jpsingleton/Huxley/pull/32.

**Comment by jpsingleton** [comment]
Roll out London for other actions and for main CRS (not just filter CRS). Support other cities too.
Allow multiple (comma separated) CRS codes to be specified in path. e.g. `all/gtw,rdh/to/lbg,vic,bfr`

**Comment by jpsingleton** [comment]
A .NET library for reading and writing CSV files: https://joshclose.github.io/CsvHelper/

**Comment by OliPicard** [comment]
I'm currently writing a Json dictionary for CRS codes. These will work nicely with most programs. Once it goes live I'd be happy to share my Json dictionary! Currently on the letter D stations.

**Comment by jpsingleton** [comment]
@OliPicard: Thanks, that sounds helpful, although it will need regular maintenance. I'd recommend using an automated process rather than doing it manually.

My current plan is to get the official list when the site starts. It's trivial to parse it and store in memory. It can then be easily serialised into JSON and I might even put in a RegEx based search.

There's an unofficial list including Lat/Long here: 
- https://github.com/markbush/openLDBWS-json/blob/master/station-codes.csv

There are also some other official data sources (including GPS Lat/Long and OS Grid References):
- http://data.gov.uk/dataset/railway-network-inspire
- http://data.gov.uk/dataset/naptan

**Comment by OliPicard** [comment]
With the help of the awesome people over at /r/learnpython I have been able to write a csv to json converter tool known as [cupid.py](https://github.com/OliPicard/cupid/blob/master/cupid.py) This should help speed up the time converting over the csv codes. I'll attempt to run it once a month and make any changes that are needed.

**Comment by jpsingleton** [comment]
https://github.com/jpsingleton/Huxley/pull/33

**Comment by jpsingleton** [comment]
**Full station names are now supported!** Including a CRS lookup or full list API. :station: :+1: :squirrel: 

The only bits left are London (and other) Terminals for all controllers and multiple CRS codes in the query path. These are both either limited to finding origins/destinations or very chatty with the API. I don't think they make sense using the SOAP back-end rather than the push port so I'm closing this issue.
