### ISSUE TITLE
Appharbor Bad Requests

### ISSUE THREAD

**Issue by Kickball** [jpsingleton/Huxley#35]
I followed the instructions on the wiki.

Forked Huxley.
Signed up to app harbor.
I then created an app in the europe region.
Then I linked my github and my app harbor.
I try to deploy the app, and app harbor says that it creates the bridge.
I am then redirected back to the root application page. (https://appharbor.com/applications/{application-name}.
It still asks me to get started, I then attempt to redeploy the app, and am given a bad request error from app harbor.
I'm able to deploy other apps to app harbor.

I am lost as to what the problem is.

**Comment by OliPicard** [comment]
Hey Kickball, Have you make sure that Nuget package restore on the app? see http://blog.appharbor.com/2012/02/06/use-nuget-package-restore-to-avoid-pushing-packages-to-appharbor

Would be good if you could post the Error log, i suspect it might be related to Nuget but being able to look at the logs is the best way forward.

Cheers
Oliver

**Comment by jpsingleton** [comment]
I've not had issues with package restore (which is enabled) but AppHarbor can be _quirky_ at times. :rage3: 
I suggest you try [the old way of integrating with GitHub](https://support.appharbor.com/kb/3rd-party-integrations/integrating-with-github) which seems to be more reliable.

To do this add AppHarbor as a service on [this page](https://github.com/Kickball/Huxley/settings/hooks) (there's a guide [here](https://developer.github.com/webhooks/#service-hooks)).
It should look like this after: 
![apphbgh](https://cloud.githubusercontent.com/assets/1695571/7551101/8b254e6e-f674-11e4-8db3-1d9ef26773bf.PNG)

After that make a tweak to the master branch (e.g. edit the README via the web interface) and it should deploy. If that doesn't work then you can clone the repository locally and push to AppHarbor as a remote.

If that fails then give Azure a go. It's much better but harder to get started.

I'll look at supporting Huxley on Linux once [CoreCLR](https://github.com/dotnet/coreclr) stabilises which should make it easy to deploy to AWS or Digital Ocean. :smiley_cat: 

Cheers
James

**Comment by Kickball** [comment]
Thanks James.

I tried what you suggested and it worked fine after that.

**Comment by jpsingleton** [comment]
No problem. Thanks for letting me know. :+1: 
I've added this info to the quick start docs.
