### ISSUE TITLE
Add support for Staff Version

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/Huxley#43]
Need access first

**Comment by jpsingleton** [comment]
Still waiting

**Comment by jamie-laundon** [comment]
Self registration for the Staff version is now available at http://openldbsv.nationalrail.co.uk/

**Comment by jpsingleton** [comment]
Thanks @jamie-laundon! That was so much easier than repeatedly chasing ATOC then printing and posting a paper form. And more importantly it's now complete (unlike the form, which I'm still waiting on).

**Comment by jamie-laundon** [comment]
No worries, I've been waiting a while too and was sent the link this afternoon.  How big a job do you think is involved to support staff version?

**Comment by jpsingleton** [comment]
I've already knocked up a quick proxy that's successfully returning live data and it looks pretty straightforward, so probably not too long to add some support. However, there is a lot more information on the staff version and many more functions available, so full support may take some time.

**Comment by jpsingleton** [comment]
There may be less to do than I thought, as not all features are available on the open version.

> There is no access to historic data via OpenLDBSVWS

This explains the unhelpful `Unexpected Server Error` I was getting.

I don't see why this isn't allowed. You could use the HSP API or log past LDB/PushPort data to get this.

**Comment by jpsingleton** [comment]
FYI, this may take a while as I have far too much on right now. The APIs are annoyingly similar but just ever-so-slightly different (looks like a classic copy-paste-change job rather than a proper refactoring). I have a basic version working but it will take some time to cleanly integrate it into the existing code. If NRE/ATOC had gotten back to me quicker then I could probably have fitted it in but I'm currently very busy.

**Comment by jpsingleton** [comment]
https://github.com/jpsingleton/Huxley/pull/47

**Comment by jalada** [comment]
This is probably a bit of an irritating question, but is there anything of note or interest in the staff version? What's the easiest way to see what is extra in the staff version? Is it best to just run the queries and see what's extra?

**Comment by jpsingleton** [comment]
I've deployed this branch to the demo server so you can [try it and see](https://huxley.apphb.com/staffall/clj?accessToken=DA1C7740-9DA0-11E4-80E6-A920340000B1&expand=true). From what I've seen it's fairly similar, but annoyingly different. There are a bunch of extra fields, some have been renamed and some have a different type. For example, the times are all now real `DateTime` objects, which is actually quite nice.

Here's an example without the service detail:

``` javascript
      "cancelReason": {
        "tiploc": "",
        "near": false,
        "value": 777
      },
      "delayReason": {
        "tiploc": "",
        "near": false,
        "value": 777
      },
      "category": "XX",
      "activities": "T           ",
      "length": 12,
      "isReverseFormation": false,
      "detachFront": false,
      "origin": [
        {
          "isOperationalEndPoint": false,
          "locationName": "Bognor Regis",
          "crs": "BOG",
          "tiploc": "BOGNORR",
          "via": null,
          "futureChangeToSpecified": false
        },
        {
          "isOperationalEndPoint": false,
          "locationName": "Fareham",
          "crs": "FRM",
          "tiploc": "FAREHAM",
          "via": null,
          "futureChangeToSpecified": false
        }
      ],
      "destination": [
        {
          "isOperationalEndPoint": false,
          "locationName": "London Victoria",
          "crs": "VIC",
          "tiploc": "VICTRIC",
          "via": null,
          "futureChangeToSpecified": false
        }
      ],
      "currentOrigins": null,
      "currentDestinations": null,
      "rid": "201609138770441",
      "uid": "W70441",
      "trainid": "1C67",
      "rsid": "SN131501",
      "sdd": "2016-09-13T00:00:00",
      "operator": "Southern",
      "operatorCode": "SN",
      "isPassengerService": true,
      "isCharter": false,
      "isCancelled": false,
      "isCircularRoute": false,
      "filterLocationCancelled": false,
      "filterLocationOperational": false,
      "isOperationalCall": false,
      "sta": "2016-09-13T16:31:00",
      "staSpecified": true,
      "ataSpecified": false,
      "eta": "2016-09-13T16:48:49",
      "etaSpecified": true,
      "arrivalType": 0,
      "arrivalTypeSpecified": true,
      "arrivalSource": null,
      "arrivalSourceInstance": null,
      "std": "2016-09-13T16:32:00",
      "stdSpecified": true,
      "atdSpecified": false,
      "etd": "2016-09-13T16:49:49",
      "etdSpecified": true,
      "departureType": 0,
      "departureTypeSpecified": true,
      "departureSource": "Darwin",
      "departureSourceInstance": null,
      "platform": "12",
      "platformIsHidden": false,
      "serviceIsSupressed": false,
      "adhocAlerts": null
```

**Comment by jamie-laundon** [comment]
Looks great, thank you for your hard work @jpsingleton

**Comment by jpsingleton** [comment]
No problem. I'll merge [the PR](https://github.com/jpsingleton/Huxley/pull/47) in and cut a new version if I don't get any issues reported reasonably soon.

Something to keep in mind with the staff service details is that you don't just get calling points. You get all locations including passed stations and junctions (for example, Borough Market Jn. and North Kent East Jn. - but you won't get a proper location for these, just a TIPLOC with whitespace trimmed).
