### ISSUE TITLE
Port to ASP.NET Core

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/Huxley#44]
Or create a new version, Huxley Core.

**Comment by jpsingleton** [comment]
I'm going to move Huxley into maintenance mode (and close all other issues) once the staff API additions have been merged in. Any major enhancements will be made in a new version targeting [.NET Core](https://www.microsoft.com/net/core) and the [.NET Standard Library](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) (once all the frameworks have been aligned).

This project will still have bug fixes and minor updates but Huxley is fairly stable now. ASP.NET Core allows for running on more platforms, plus I can't really write [a book](https://unop.uk/book/) on it and not aim to support it. :smile: 

:shipit:

**Comment by nullpixel** [comment]
Did this stall?

**Comment by jpsingleton** [comment]
Yep. I've been busy with other things. Low priority TBH.

**Comment by nullpixel** [comment]
Ah, fair enough

**Comment by revitteth** [comment]
Ooo, I came here and got excited when I saw this. Might contribute back if I get time to port to core :)

**Comment by jpsingleton** [comment]
Cheers. I am working on it but it keeps getting pushed down the 
priorities. Although as I can see there is demand for it I'll try and 
bump it up. I have lots of ideas for improvements so it will be more of 
a rewrite than a port.


Thanks,
James Singleton

------------------------------------------------------------------------

*What's Your Problem?*

I solve business problems with technology. If you've got a business 
problem then get in touch for a free consultation. I'd /love/ to hear 
about your biggest business problems.

*My Email*: jpsingleton@gmail.com <mailto:jpsingleton@gmail.com>
*Tech Blog*: unop.uk <https://unop.uk/>

**Comment by revitteth** [comment]
Sounds good man, do we know much about the national rail software upgrade timelines? Surely at some point they are going to retire this SOAP arch? Contemplating doing something with Go but painful with the WSDLs.

**Comment by jpsingleton** [comment]
I wouldn't count on it. The railways are far from early adopters and 
have an outsourced enterprise software culture. I see this SOAP API 
sticking around for a long time. Lots of things rely on it, including a 
great deal of the customer information systems at stations all over GB.

Feel free to use the current version of Huxley to proxy the SOAP calls. 
Any future version will be backward compatible with the current web API, 
but may extend it.


Thanks,
James Singleton

------------------------------------------------------------------------

*What's Your Problem?*

I solve business problems with technology. If you've got a business 
problem then get in touch for a free consultation. I'd /love/ to hear 
about your biggest business problems.

*My Email*: jpsingleton@gmail.com <mailto:jpsingleton@gmail.com>
*Tech Blog*: unop.uk <https://unop.uk/>

**Comment by jpsingleton** [comment]
Almost ready. [Blog post](https://unop.uk/huxley-2/), [demo server](https://huxley2.azurewebsites.net/).

**Comment by nullpixel** [comment]
Woah, exceptional work!

**Comment by jpsingleton** [comment]
[Huxley 2](https://github.com/jpsingleton/Huxley2) is [out now](https://unop.uk/huxley-2-release/)!
