### ISSUE TITLE
Unable to get CallingPoints data

### ISSUE THREAD

**Issue by mooomaaan** [jpsingleton/Huxley#51]
I'm not the greatest developer, however I am finding it impossible to get the data for where the train is calling at. I might be wrong. If I am not wrong, is there any way I can edit a script to provide me that data?

**Comment by jpsingleton** [comment]
To get the calling points you either need to add the `expand=true` query string parameter to a board API endpoint or query the service API endpoint with the ID of the service (from the board API response).
