### ISSUE TITLE
Error 500 Issues with new serviceID format

### ISSUE THREAD

**Issue by jasonkapadia** [jpsingleton/Huxley#55]
Hi, I see there is a fix on Huxley2. Will there be one for the legacy Huxley?

Many thanks

Describe the bug
Huxley 2 appears to be unable to interpret the new-format Darwin Service IDs - as such, all queries that hit a new Darwin server (which now appears to be the majority?) will error out

To Reproduce
Query any previously valid route

Expected behaviour
Information Returned

Actual Behaviour

Error 500 returned

**Comment by jpsingleton** [comment]
I'm not planning to update Huxley. I haven't coded on Windows in years.

The best option is to upgrade to Huxley 2 once it is fixed. However, if someone wants to back-port the fix and test it then I'm happy to merge a PR.

Links to Huxley 2 issue / PR: https://github.com/jpsingleton/Huxley2/issues/13 / https://github.com/jpsingleton/Huxley2/pull/14
