### ISSUE TITLE
Add TfL APIs to proxy

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/Huxley#7]
Although the TfL APIs are restful they only return XML and are not cross domain. Proxy these to JSON with CORS headers. Access tokens aren't required.

Example here: https://tube.apphb.com/proxy/tube?format=json

Maybe include other APIs apart from just line status (http://cloud.tfl.gov.uk/TrackerNet/LineStatus)?

TfL APIs are in Azure (Dublin or Amsterdam?) whereas NRE are in AWS (Dublin) so is it worth combining these projects?
The main TfL site looks like it's in AWS so maybe do this if / when they migrate.

**Comment by danmewett** [comment]
If you want to tfl arrivals across all modes including tube bus overground in JSON format you should use api.tfl.gov.uk.  There are endpoints for line arrivals and stoppoint arrivals.

**Comment by danmewett** [comment]
Examples: 
victoria line tube- http://api.tfl.gov.uk/line/victoria/arrivals
Number 10 bus - http://api.tfl.gov.uk/line/10/arrivals

Arrivals at Brixton Underground station: http://api.tfl.gov.uk/StopPoint/940GZZLUBXN/arrivals
Arrivals at Tottenham Court Road bus stop X: http://api.tfl.gov.uk/StopPoint/490000235X/arrivals

**Comment by jpsingleton** [comment]
Thanks! Looks like https://api.tfl.gov.uk/line/mode/tube,overground,dlr/status is exactly what I was looking for and it even has CORS headers. Plus it's in AWS in Dublin so low latency.

No need to integrate this into Huxley as it can be used directly so I'll close the issue. I wish NRE were as good as TfL are with APIs. Very similar stacks too.
